### PR TITLE
Made a structure for to-do list with some style

### PR DESCRIPTION
**Pull request by Rishi-Mishra0704**
## List Structure of to-do list project

**_In this PR , I made a to-do list's basic structure with some styles_**

#### Key features :-

-  Made a basic structure for list
-  Add hover effect to the clear all button
-  Adjust margin and padding

### CODE REVIEW

**Comment by Rishi-Mishra0704** [comment]
There was a typo when creating the .github/workflows

**Review by levy002 — COMMENTED** [review]
## Hello @Rishi-Mishra0704 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

- [ ] You have submitted a project, that has a README with the information of another project different from the current one you are working on. Kindly customize the README file in order to provide the information of the `TO-DO LIST` project because at this moment we have information for the`AWESOME BOOKS`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by frank1738 — COMMENTED** [review]
Hi @Rishi-Mishra0704 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] as stated earlier,  Some information on your readme contains `AWESOME-BOOKS`  data.  Kindly adjust that

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Mihndim2020 — CHANGES_REQUESTED** [review]
### Hi @Rishi-Mishra0704, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to get this project approved, but you are almost there!
ALMOST-MINION

# Status: Requires Changes ♻️
_Check the comments under the review._

### Please I will this comments here since you did not make any changes in the concerned files
Please make sure:
- [ ] Please make sure webpack dev server is set up and running with no errors as this will enable us to run your project. 
- [ ] Please make sure the HTML file configured in the Webpack config settings as a template using the *HTML Webpack Plugin*.
- [ ] Make sure your project is running and meets the [design specifications.](https://www.youtube.com/watch?v=AcUd-_Yjjqg) 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Rishi-Mishra0704** [comment]
**_As there is no requirement for functionality the project is completely static and has no functionality_**

- Update package.json with dev-server
- add html plugins

**Comment by Rishi-Mishra0704** [comment]
## To run the project 

please enter  **npm start** start in CLI

**Review by mikethreels — COMMENTED** [review]
Hi Rishi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
